#for x86_64 architecture
#FROM openjdk:17-jdk-alpine

FROM eclipse-temurin:17-jdk


#for ARM64 architecture
#FROM --platform=linux/arm64 eclipse-temurin:17-jdk

COPY target/*.jar app.jar
ENV server.port=8081
#ENTRYPOINT ["java",  "-Dspring.profiles.active=dev", "-jar","/app.jar"]
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-Dmanagement.metrics.binders.system.enabled=false", "-jar", "/app.jar"]

